// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAOA7cXzwZlA82YaXsQU50YzKFwz57Y30',
    appId: '1:128754816574:web:0ace2ff63cf470d253a36f',
    messagingSenderId: '128754816574',
    projectId: 'projectcba-bda97',
    authDomain: 'projectcba-bda97.firebaseapp.com',
    storageBucket: 'projectcba-bda97.appspot.com',
    measurementId: 'G-5LX0C7ZF0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCnkUfrQVSshR8ODVA73PzhoKRZoY-TSs',
    appId: '1:128754816574:android:0ace6831d25b1dea53a36f',
    messagingSenderId: '128754816574',
    projectId: 'projectcba-bda97',
    storageBucket: 'projectcba-bda97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiXYuRPMAcH4CsQmQkvFM3CaitAdSuGVk',
    appId: '1:128754816574:ios:44f0ac40a9671f5053a36f',
    messagingSenderId: '128754816574',
    projectId: 'projectcba-bda97',
    storageBucket: 'projectcba-bda97.appspot.com',
    iosBundleId: 'com.example.tiendaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiXYuRPMAcH4CsQmQkvFM3CaitAdSuGVk',
    appId: '1:128754816574:ios:44f0ac40a9671f5053a36f',
    messagingSenderId: '128754816574',
    projectId: 'projectcba-bda97',
    storageBucket: 'projectcba-bda97.appspot.com',
    iosBundleId: 'com.example.tiendaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAOA7cXzwZlA82YaXsQU50YzKFwz57Y30',
    appId: '1:128754816574:web:4c97fa7e4275964853a36f',
    messagingSenderId: '128754816574',
    projectId: 'projectcba-bda97',
    authDomain: 'projectcba-bda97.firebaseapp.com',
    storageBucket: 'projectcba-bda97.appspot.com',
    measurementId: 'G-HSHWK45NGH',
  );
}
