// ignore_for_file: file_names

class EventosLiderClase {
  final String? titulo,
      fecha,
      usuario,
      tipoDocumento,
      documento,
      correo,
      telefono1,
      telefono2;

  EventosLiderClase(
      {required this.titulo,
      required this.fecha,
      required this.usuario,
      required this.tipoDocumento,
      required this.documento,
      required this.correo,
      required this.telefono1,
      required this.telefono2});
}

List<EventosLiderClase> eventoLiderList = [
  EventosLiderClase(
    titulo: "Subasta de porcinos CBA",
    fecha: "20-05-2024:12:00",
    usuario: "Mario Pedraza",
    tipoDocumento: "C.C",
    documento: "345678902",
    correo: "mario29@gmail.com",
    telefono1: "8308976",
    telefono2: "3118901256",
  ),
  EventosLiderClase(
    titulo: "Subasta de porcinos CBA",
    fecha: "20-05-2024:12:00",
    usuario: "Mario Pedraza",
    tipoDocumento: "C.C",
    documento: "345678902",
    correo: "mario29@gmail.com",
    telefono1: "8308976",
    telefono2: "3118901256",
  ),
  EventosLiderClase(
    titulo: "Subasta de porcinos CBA",
    fecha: "20-05-2024:12:00",
    usuario: "Mario Pedraza",
    tipoDocumento: "C.C",
    documento: "345678902",
    correo: "mario29@gmail.com",
    telefono1: "8308976",
    telefono2: "3118901256",
  ),
  EventosLiderClase(
    titulo: "Subasta de porcinos CBA",
    fecha: "20-05-2024:12:00",
    usuario: "Mario Pedraza",
    tipoDocumento: "C.C",
    documento: "345678902",
    correo: "mario29@gmail.com",
    telefono1: "8308976",
    telefono2: "3118901256",
  ),
  EventosLiderClase(
    titulo: "Subasta de porcinos CBA",
    fecha: "20-05-2024:12:00",
    usuario: "Mario Pedraza",
    tipoDocumento: "C.C",
    documento: "345678902",
    correo: "mario29@gmail.com",
    telefono1: "8308976",
    telefono2: "3118901256",
  ),
  EventosLiderClase(
    titulo: "Subasta de porcinos CBA",
    fecha: "20-05-2024:12:00",
    usuario: "Mario Pedraza",
    tipoDocumento: "C.C",
    documento: "345678902",
    correo: "mario29@gmail.com",
    telefono1: "8308976",
    telefono2: "3118901256",
  ),
  EventosLiderClase(
    titulo: "Subasta de porcinos CBA",
    fecha: "20-05-2024:12:00",
    usuario: "Mario Pedraza",
    tipoDocumento: "C.C",
    documento: "345678902",
    correo: "mario29@gmail.com",
    telefono1: "8308976",
    telefono2: "3118901256",
  ),
  EventosLiderClase(
    titulo: "Subasta de porcinos CBA",
    fecha: "20-05-2024:12:00",
    usuario: "Mario Pedraza",
    tipoDocumento: "C.C",
    documento: "345678902",
    correo: "mario29@gmail.com",
    telefono1: "8308976",
    telefono2: "3118901256",
  ),
  EventosLiderClase(
    titulo: "Subasta de porcinos CBA",
    fecha: "20-05-2024:12:00",
    usuario: "Mario Pedraza",
    tipoDocumento: "C.C",
    documento: "345678902",
    correo: "mario29@gmail.com",
    telefono1: "8308976",
    telefono2: "3118901256",
  ),
  EventosLiderClase(
    titulo: "Subasta de porcinos CBA",
    fecha: "20-05-2024:12:00",
    usuario: "Mario Pedraza",
    tipoDocumento: "C.C",
    documento: "345678902",
    correo: "mario29@gmail.com",
    telefono1: "8308976",
    telefono2: "3118901256",
  ),
];

class PedidoLider {
  final String? numero,
      usuario,
      producto,
      cantidad,
      precio,
      fechaEncargo,
      fechaEntrega,
      grupal,
      puntoVenta;

  PedidoLider(
      {required this.numero,
      required this.usuario,
      required this.producto,
      required this.cantidad,
      required this.precio,
      required this.fechaEncargo,
      required this.fechaEntrega,
      required this.grupal,
      required this.puntoVenta});
}

List<PedidoLider> pedidoLiderList = [
  PedidoLider(
      numero: "1005",
      usuario: "María Contreras",
      producto: "Cubeta de huevos AA",
      cantidad: "2",
      precio: "32.000",
      fechaEncargo: "20-05-2024:12:20",
      fechaEntrega: "25-05-2024:3:40",
      grupal: "Si",
      puntoVenta: "Portería CBA"),
  PedidoLider(
      numero: "1005",
      usuario: "María Contreras",
      producto: "Cubeta de huevos AA",
      cantidad: "2",
      precio: "32.000",
      fechaEncargo: "20-05-2024:12:20",
      fechaEntrega: "25-05-2024:3:40",
      grupal: "Si",
      puntoVenta: "Portería CBA"),
  PedidoLider(
      numero: "1005",
      usuario: "María Contreras",
      producto: "Cubeta de huevos AA",
      cantidad: "2",
      precio: "32.000",
      fechaEncargo: "20-05-2024:12:20",
      fechaEntrega: "25-05-2024:3:40",
      grupal: "Si",
      puntoVenta: "Portería CBA"),
  PedidoLider(
      numero: "1005",
      usuario: "María Contreras",
      producto: "Cubeta de huevos AA",
      cantidad: "2",
      precio: "32.000",
      fechaEncargo: "20-05-2024:12:20",
      fechaEntrega: "25-05-2024:3:40",
      grupal: "Si",
      puntoVenta: "Portería CBA"),
  PedidoLider(
      numero: "1005",
      usuario: "María Contreras",
      producto: "Cubeta de huevos AA",
      cantidad: "2",
      precio: "32.000",
      fechaEncargo: "20-05-2024:12:20",
      fechaEntrega: "25-05-2024:3:40",
      grupal: "Si",
      puntoVenta: "Portería CBA"),
  PedidoLider(
      numero: "1005",
      usuario: "María Contreras",
      producto: "Cubeta de huevos AA",
      cantidad: "2",
      precio: "32.000",
      fechaEncargo: "20-05-2024:12:20",
      fechaEntrega: "25-05-2024:3:40",
      grupal: "Si",
      puntoVenta: "Portería CBA"),
  PedidoLider(
      numero: "1005",
      usuario: "María Contreras",
      producto: "Cubeta de huevos AA",
      cantidad: "2",
      precio: "32.000",
      fechaEncargo: "20-05-2024:12:20",
      fechaEntrega: "25-05-2024:3:40",
      grupal: "Si",
      puntoVenta: "Portería CBA"),
  PedidoLider(
      numero: "1005",
      usuario: "María Contreras",
      producto: "Cubeta de huevos AA",
      cantidad: "2",
      precio: "32.000",
      fechaEncargo: "20-05-2024:12:20",
      fechaEntrega: "25-05-2024:3:40",
      grupal: "Si",
      puntoVenta: "Portería CBA"),
  PedidoLider(
      numero: "1005",
      usuario: "María Contreras",
      producto: "Cubeta de huevos AA",
      cantidad: "2",
      precio: "32.000",
      fechaEncargo: "20-05-2024:12:20",
      fechaEntrega: "25-05-2024:3:40",
      grupal: "Si",
      puntoVenta: "Portería CBA"),
  PedidoLider(
      numero: "1005",
      usuario: "María Contreras",
      producto: "Cubeta de huevos AA",
      cantidad: "2",
      precio: "32.000",
      fechaEncargo: "20-05-2024:12:20",
      fechaEntrega: "25-05-2024:3:40",
      grupal: "Si",
      puntoVenta: "Portería CBA"),
];

class FacturaLiderClase {
  final String? numero,
      usuario,
      numeroPedido,
      producto,
      fecha,
      valorPedido,
      medioPago;

  FacturaLiderClase(
      {required this.numero,
      required this.usuario,
      required this.numeroPedido,
      required this.producto,
      required this.fecha,
      required this.valorPedido,
      required this.medioPago});
}

List<FacturaLiderClase> facturaLiderList = [
  FacturaLiderClase(
      numero: "200",
      usuario: "Francisco Pelaez",
      numeroPedido: "1006",
      producto: "Carne de res",
      fecha: "31-05-2024:14:21",
      valorPedido: "11.000",
      medioPago: "Efectivo"),
  FacturaLiderClase(
      numero: "200",
      usuario: "Francisco Pelaez",
      numeroPedido: "1006",
      producto: "Carne de res",
      fecha: "31-05-2024:14:21",
      valorPedido: "11.000",
      medioPago: "Efectivo"),
  FacturaLiderClase(
      numero: "200",
      usuario: "Francisco Pelaez",
      numeroPedido: "1006",
      producto: "Carne de res",
      fecha: "31-05-2024:14:21",
      valorPedido: "11.000",
      medioPago: "Efectivo"),
  FacturaLiderClase(
      numero: "200",
      usuario: "Francisco Pelaez",
      numeroPedido: "1006",
      producto: "Carne de res",
      fecha: "31-05-2024:14:21",
      valorPedido: "11.000",
      medioPago: "Efectivo"),
  FacturaLiderClase(
      numero: "200",
      usuario: "Francisco Pelaez",
      numeroPedido: "1006",
      producto: "Carne de res",
      fecha: "31-05-2024:14:21",
      valorPedido: "11.000",
      medioPago: "Efectivo"),
  FacturaLiderClase(
      numero: "200",
      usuario: "Francisco Pelaez",
      numeroPedido: "1006",
      producto: "Carne de res",
      fecha: "31-05-2024:14:21",
      valorPedido: "11.000",
      medioPago: "Efectivo"),
  FacturaLiderClase(
      numero: "200",
      usuario: "Francisco Pelaez",
      numeroPedido: "1006",
      producto: "Carne de res",
      fecha: "31-05-2024:14:21",
      valorPedido: "11.000",
      medioPago: "Efectivo"),
  FacturaLiderClase(
      numero: "200",
      usuario: "Francisco Pelaez",
      numeroPedido: "1006",
      producto: "Carne de res",
      fecha: "31-05-2024:14:21",
      valorPedido: "11.000",
      medioPago: "Efectivo"),
  FacturaLiderClase(
      numero: "200",
      usuario: "Francisco Pelaez",
      numeroPedido: "1006",
      producto: "Carne de res",
      fecha: "31-05-2024:14:21",
      valorPedido: "11.000",
      medioPago: "Efectivo"),
  FacturaLiderClase(
      numero: "200",
      usuario: "Francisco Pelaez",
      numeroPedido: "1006",
      producto: "Carne de res",
      fecha: "31-05-2024:14:21",
      valorPedido: "11.000",
      medioPago: "Efectivo"),
];

class DevolucionLiderClase {
  final String? numeroVenta,
      usuario,
      numeroPedido,
      producto,
      fechaVenta,
      valorPedido,
      medioPago,
      fecha,
      estado;

  DevolucionLiderClase(
      {required this.numeroVenta,
      required this.usuario,
      required this.numeroPedido,
      required this.producto,
      required this.fechaVenta,
      required this.valorPedido,
      required this.medioPago,
      required this.fecha,
      required this.estado});
}

List<DevolucionLiderClase> devolucionLiderList = [
  DevolucionLiderClase(
      numeroVenta: "2005",
      usuario: "Juan Cardona",
      numeroPedido: "1007",
      producto: "Leche de cabra",
      fechaVenta: "30-05-2024:16:00",
      valorPedido: "7.000",
      medioPago: "Pasarela",
      fecha: "01-06-2024:8:00",
      estado: "Cancelado"),
  DevolucionLiderClase(
      numeroVenta: "2005",
      usuario: "Juan Cardona",
      numeroPedido: "1007",
      producto: "Leche de cabra",
      fechaVenta: "30-05-2024:16:00",
      valorPedido: "7.000",
      medioPago: "Pasarela",
      fecha: "01-06-2024:8:00",
      estado: "Cancelado"),
  DevolucionLiderClase(
      numeroVenta: "2005",
      usuario: "Juan Cardona",
      numeroPedido: "1007",
      producto: "Leche de cabra",
      fechaVenta: "30-05-2024:16:00",
      valorPedido: "7.000",
      medioPago: "Pasarela",
      fecha: "01-06-2024:8:00",
      estado: "Cancelado"),
  DevolucionLiderClase(
      numeroVenta: "2005",
      usuario: "Juan Cardona",
      numeroPedido: "1007",
      producto: "Leche de cabra",
      fechaVenta: "30-05-2024:16:00",
      valorPedido: "7.000",
      medioPago: "Pasarela",
      fecha: "01-06-2024:8:00",
      estado: "Cancelado"),
  DevolucionLiderClase(
      numeroVenta: "2005",
      usuario: "Juan Cardona",
      numeroPedido: "1007",
      producto: "Leche de cabra",
      fechaVenta: "30-05-2024:16:00",
      valorPedido: "7.000",
      medioPago: "Pasarela",
      fecha: "01-06-2024:8:00",
      estado: "Cancelado"),
  DevolucionLiderClase(
      numeroVenta: "2005",
      usuario: "Juan Cardona",
      numeroPedido: "1007",
      producto: "Leche de cabra",
      fechaVenta: "30-05-2024:16:00",
      valorPedido: "7.000",
      medioPago: "Pasarela",
      fecha: "01-06-2024:8:00",
      estado: "Cancelado"),
  DevolucionLiderClase(
      numeroVenta: "2005",
      usuario: "Juan Cardona",
      numeroPedido: "1007",
      producto: "Leche de cabra",
      fechaVenta: "30-05-2024:16:00",
      valorPedido: "7.000",
      medioPago: "Pasarela",
      fecha: "01-06-2024:8:00",
      estado: "Cancelado"),
  DevolucionLiderClase(
      numeroVenta: "2005",
      usuario: "Juan Cardona",
      numeroPedido: "1007",
      producto: "Leche de cabra",
      fechaVenta: "30-05-2024:16:00",
      valorPedido: "7.000",
      medioPago: "Pasarela",
      fecha: "01-06-2024:8:00",
      estado: "Cancelado"),
  DevolucionLiderClase(
      numeroVenta: "2005",
      usuario: "Juan Cardona",
      numeroPedido: "1007",
      producto: "Leche de cabra",
      fechaVenta: "30-05-2024:16:00",
      valorPedido: "7.000",
      medioPago: "Pasarela",
      fecha: "01-06-2024:8:00",
      estado: "Cancelado"),
  DevolucionLiderClase(
      numeroVenta: "2005",
      usuario: "Juan Cardona",
      numeroPedido: "1007",
      producto: "Leche de cabra",
      fechaVenta: "30-05-2024:16:00",
      valorPedido: "7.000",
      medioPago: "Pasarela",
      fecha: "01-06-2024:8:00",
      estado: "Cancelado"),
];

class ProduccionLiderClase {
  final String? numero,
      unidadProduccion,
      producto,
      cantidad,
      fechaProduccion,
      fechaVencimiento,
      costoProduccion,
      fechaDespacho,
      estado;

  ProduccionLiderClase(
      {required this.numero,
      required this.unidadProduccion,
      required this.producto,
      required this.cantidad,
      required this.fechaProduccion,
      required this.fechaVencimiento,
      required this.costoProduccion,
      required this.fechaDespacho,
      required this.estado});
}

List<ProduccionLiderClase> produccionLiderList = [
  ProduccionLiderClase(
      numero: "4000",
      unidadProduccion: "Cultivo",
      producto: "Astromelias Ramo",
      cantidad: "30",
      fechaProduccion: "11-06-2024",
      fechaVencimiento: "",
      costoProduccion: "10.000.000",
      fechaDespacho: "16-06-2024",
      estado: "Despachado"),
  ProduccionLiderClase(
      numero: "4000",
      unidadProduccion: "Cultivo",
      producto: "Astromelias Ramo",
      cantidad: "30",
      fechaProduccion: "11-06-2024",
      fechaVencimiento: "",
      costoProduccion: "10.000.000",
      fechaDespacho: "16-06-2024",
      estado: "Despachado"),
  ProduccionLiderClase(
      numero: "4000",
      unidadProduccion: "Cultivo",
      producto: "Astromelias Ramo",
      cantidad: "30",
      fechaProduccion: "11-06-2024",
      fechaVencimiento: "",
      costoProduccion: "10.000.000",
      fechaDespacho: "16-06-2024",
      estado: "Despachado"),
  ProduccionLiderClase(
      numero: "4000",
      unidadProduccion: "Cultivo",
      producto: "Astromelias Ramo",
      cantidad: "30",
      fechaProduccion: "11-06-2024",
      fechaVencimiento: "",
      costoProduccion: "10.000.000",
      fechaDespacho: "16-06-2024",
      estado: "Despachado"),
  ProduccionLiderClase(
      numero: "4000",
      unidadProduccion: "Cultivo",
      producto: "Astromelias Ramo",
      cantidad: "30",
      fechaProduccion: "11-06-2024",
      fechaVencimiento: "",
      costoProduccion: "10.000.000",
      fechaDespacho: "16-06-2024",
      estado: "Despachado"),
  ProduccionLiderClase(
      numero: "4000",
      unidadProduccion: "Cultivo",
      producto: "Astromelias Ramo",
      cantidad: "30",
      fechaProduccion: "11-06-2024",
      fechaVencimiento: "",
      costoProduccion: "10.000.000",
      fechaDespacho: "16-06-2024",
      estado: "Despachado"),
  ProduccionLiderClase(
      numero: "4000",
      unidadProduccion: "Cultivo",
      producto: "Astromelias Ramo",
      cantidad: "30",
      fechaProduccion: "11-06-2024",
      fechaVencimiento: "",
      costoProduccion: "10.000.000",
      fechaDespacho: "16-06-2024",
      estado: "Despachado"),
  ProduccionLiderClase(
      numero: "4000",
      unidadProduccion: "Cultivo",
      producto: "Astromelias Ramo",
      cantidad: "30",
      fechaProduccion: "11-06-2024",
      fechaVencimiento: "",
      costoProduccion: "10.000.000",
      fechaDespacho: "16-06-2024",
      estado: "Despachado"),
  ProduccionLiderClase(
      numero: "4000",
      unidadProduccion: "Cultivo",
      producto: "Astromelias Ramo",
      cantidad: "30",
      fechaProduccion: "11-06-2024",
      fechaVencimiento: "",
      costoProduccion: "10.000.000",
      fechaDespacho: "16-06-2024",
      estado: "Despachado"),
  ProduccionLiderClase(
      numero: "4000",
      unidadProduccion: "Cultivo",
      producto: "Astromelias Ramo",
      cantidad: "30",
      fechaProduccion: "11-06-2024",
      fechaVencimiento: "",
      costoProduccion: "10.000.000",
      fechaDespacho: "16-06-2024",
      estado: "Despachado"),
];

class BodegaLiderClase {
  final String? producto,
      numeroProduccion,
      unidadProduccion,
      cantidadEnviada,
      cantidadLlegada,
      cantidadBodega,
      fechaInventario,
      puntoVenta;

  BodegaLiderClase(
      {required this.producto,
      required this.numeroProduccion,
      required this.unidadProduccion,
      required this.cantidadEnviada,
      required this.cantidadLlegada,
      required this.cantidadBodega,
      required this.fechaInventario,
      required this.puntoVenta});
}

List<BodegaLiderClase> bodegaLiderList = [
  BodegaLiderClase(
      producto: "Mango",
      numeroProduccion: "4005",
      unidadProduccion: "Frutas",
      cantidadEnviada: "60",
      cantidadLlegada: "59",
      cantidadBodega: "120",
      fechaInventario: "13-06-2024:11:00",
      puntoVenta: "Portería CBA"),
  BodegaLiderClase(
      producto: "Mango",
      numeroProduccion: "4005",
      unidadProduccion: "Frutas",
      cantidadEnviada: "60",
      cantidadLlegada: "59",
      cantidadBodega: "120",
      fechaInventario: "13-06-2024:11:00",
      puntoVenta: "Portería CBA"),
  BodegaLiderClase(
      producto: "Mango",
      numeroProduccion: "4005",
      unidadProduccion: "Frutas",
      cantidadEnviada: "60",
      cantidadLlegada: "59",
      cantidadBodega: "120",
      fechaInventario: "13-06-2024:11:00",
      puntoVenta: "Portería CBA"),
  BodegaLiderClase(
      producto: "Mango",
      numeroProduccion: "4005",
      unidadProduccion: "Frutas",
      cantidadEnviada: "60",
      cantidadLlegada: "59",
      cantidadBodega: "120",
      fechaInventario: "13-06-2024:11:00",
      puntoVenta: "Portería CBA"),
  BodegaLiderClase(
      producto: "Mango",
      numeroProduccion: "4005",
      unidadProduccion: "Frutas",
      cantidadEnviada: "60",
      cantidadLlegada: "59",
      cantidadBodega: "120",
      fechaInventario: "13-06-2024:11:00",
      puntoVenta: "Portería CBA"),
  BodegaLiderClase(
      producto: "Mango",
      numeroProduccion: "4005",
      unidadProduccion: "Frutas",
      cantidadEnviada: "60",
      cantidadLlegada: "59",
      cantidadBodega: "120",
      fechaInventario: "13-06-2024:11:00",
      puntoVenta: "Portería CBA"),
  BodegaLiderClase(
      producto: "Mango",
      numeroProduccion: "4005",
      unidadProduccion: "Frutas",
      cantidadEnviada: "60",
      cantidadLlegada: "59",
      cantidadBodega: "120",
      fechaInventario: "13-06-2024:11:00",
      puntoVenta: "Portería CBA"),
  BodegaLiderClase(
      producto: "Mango",
      numeroProduccion: "4005",
      unidadProduccion: "Frutas",
      cantidadEnviada: "60",
      cantidadLlegada: "59",
      cantidadBodega: "120",
      fechaInventario: "13-06-2024:11:00",
      puntoVenta: "Portería CBA"),
  BodegaLiderClase(
      producto: "Mango",
      numeroProduccion: "4005",
      unidadProduccion: "Frutas",
      cantidadEnviada: "60",
      cantidadLlegada: "59",
      cantidadBodega: "120",
      fechaInventario: "13-06-2024:11:00",
      puntoVenta: "Portería CBA"),
  BodegaLiderClase(
      producto: "Mango",
      numeroProduccion: "4005",
      unidadProduccion: "Frutas",
      cantidadEnviada: "60",
      cantidadLlegada: "59",
      cantidadBodega: "120",
      fechaInventario: "13-06-2024:11:00",
      puntoVenta: "Portería CBA"),
];

class UsuarioLiderClase {
  final String? usuario,
      tipoDocumento,
      documento,
      correo,
      telefono1,
      telefono2,
      rol1,
      rol2,
      rol3,
      estado;

  UsuarioLiderClase(
      {required this.usuario,
      required this.tipoDocumento,
      required this.documento,
      required this.correo,
      required this.telefono1,
      required this.telefono2,
      required this.rol1,
      required this.rol2,
      required this.rol3,
      required this.estado});
}

List<UsuarioLiderClase> usuarioLiderList = [
  UsuarioLiderClase(
      usuario: "Marina Perea",
      tipoDocumento: "C.E",
      documento: "24453343223",
      correo: "marinape21@gmail.com",
      telefono1: "8707654",
      telefono2: "3158907654",
      rol1: "Aprendiz",
      rol2: "",
      rol3: "",
      estado: "Activo"),
  UsuarioLiderClase(
      usuario: "Marina Perea",
      tipoDocumento: "C.E",
      documento: "24453343223",
      correo: "marinape21@gmail.com",
      telefono1: "8707654",
      telefono2: "3158907654",
      rol1: "Aprendiz",
      rol2: "",
      rol3: "",
      estado: "Activo"),
  UsuarioLiderClase(
      usuario: "Marina Perea",
      tipoDocumento: "C.E",
      documento: "24453343223",
      correo: "marinape21@gmail.com",
      telefono1: "8707654",
      telefono2: "3158907654",
      rol1: "Aprendiz",
      rol2: "",
      rol3: "",
      estado: "Activo"),
  UsuarioLiderClase(
      usuario: "Marina Perea",
      tipoDocumento: "C.E",
      documento: "24453343223",
      correo: "marinape21@gmail.com",
      telefono1: "8707654",
      telefono2: "3158907654",
      rol1: "Aprendiz",
      rol2: "",
      rol3: "",
      estado: "Activo"),
  UsuarioLiderClase(
      usuario: "Marina Perea",
      tipoDocumento: "C.E",
      documento: "24453343223",
      correo: "marinape21@gmail.com",
      telefono1: "8707654",
      telefono2: "3158907654",
      rol1: "Aprendiz",
      rol2: "",
      rol3: "",
      estado: "Activo"),
  UsuarioLiderClase(
      usuario: "Marina Perea",
      tipoDocumento: "C.E",
      documento: "24453343223",
      correo: "marinape21@gmail.com",
      telefono1: "8707654",
      telefono2: "3158907654",
      rol1: "Aprendiz",
      rol2: "",
      rol3: "",
      estado: "Activo"),
  UsuarioLiderClase(
      usuario: "Marina Perea",
      tipoDocumento: "C.E",
      documento: "24453343223",
      correo: "marinape21@gmail.com",
      telefono1: "8707654",
      telefono2: "3158907654",
      rol1: "Aprendiz",
      rol2: "",
      rol3: "",
      estado: "Activo"),
  UsuarioLiderClase(
      usuario: "Marina Perea",
      tipoDocumento: "C.E",
      documento: "24453343223",
      correo: "marinape21@gmail.com",
      telefono1: "8707654",
      telefono2: "3158907654",
      rol1: "Aprendiz",
      rol2: "",
      rol3: "",
      estado: "Activo"),
  UsuarioLiderClase(
      usuario: "Marina Perea",
      tipoDocumento: "C.E",
      documento: "24453343223",
      correo: "marinape21@gmail.com",
      telefono1: "8707654",
      telefono2: "3158907654",
      rol1: "Aprendiz",
      rol2: "",
      rol3: "",
      estado: "Activo"),
  UsuarioLiderClase(
      usuario: "Marina Perea",
      tipoDocumento: "C.E",
      documento: "24453343223",
      correo: "marinape21@gmail.com",
      telefono1: "8707654",
      telefono2: "3158907654",
      rol1: "Aprendiz",
      rol2: "",
      rol3: "",
      estado: "Activo"),
];
